version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - '5432:5432'  
volumes:
  postgres:
    name: tempus-db