version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - '5432:5432'
  backend:
    container_name: tempus-backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.prod
  
volumes:
  postgres:
    name: tempus-db